name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - lucferbux
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please, fill this form to help us improve the project.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is and how often it occurs
      placeholder: Tell us what you see!
      value: |
          **Steps To Reproduce**
          Steps to reproduce the behavior:
          1. Go to '...'
          2. Click on '....'
          3. Scroll down to '....'
          4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Tell us what was the expected behavior!
    validations:
      required: true
  - type: textarea
    id: workaround
    attributes:
      label: Workaround (if any)
      description: Any manual steps that allow you to resolve the issue
      placeholder: Tell us the steps you followed to resolve the issue!
    validations:
      required: false
  - type: dropdown
    id: openshift-version
    attributes:
      label: Openshift Version
      description: What version of Openshift are you running?
      options:
        - Baremetal
        - OpenStack
        - RHV
        - AWS
        - OKD
        - CodeReady Containers
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: false
  - type: textarea
    id: opendatahub-version
    attributes:
      label: Open Data Hub Version
      description: Please attach relevant kfdef manifest if applicable
      render: yaml
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
